set(_CATKIN_CURRENT_PACKAGE "hough_drive")
set(hough_drive_VERSION "0.0.0")
set(hough_drive_MAINTAINER "nvidia <nvidia@todo.todo>")
set(hough_drive_PACKAGE_FORMAT "2")
set(hough_drive_BUILD_DEPENDS "rospy")
set(hough_drive_BUILD_EXPORT_DEPENDS "rospy")
set(hough_drive_BUILDTOOL_DEPENDS "catkin")
set(hough_drive_BUILDTOOL_EXPORT_DEPENDS )
set(hough_drive_EXEC_DEPENDS "rospy")
set(hough_drive_RUN_DEPENDS "rospy")
set(hough_drive_TEST_DEPENDS )
set(hough_drive_DOC_DEPENDS )
set(hough_drive_URL_WEBSITE "")
set(hough_drive_URL_BUGTRACKER "")
set(hough_drive_URL_REPOSITORY "")
set(hough_drive_DEPRECATED "")