set(_CATKIN_CURRENT_PACKAGE "my_lidar")
set(my_lidar_VERSION "0.0.0")
set(my_lidar_MAINTAINER "nvidia <nvidia@todo.todo>")
set(my_lidar_PACKAGE_FORMAT "2")
set(my_lidar_BUILD_DEPENDS "rospy" "std_msgs")
set(my_lidar_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(my_lidar_BUILDTOOL_DEPENDS "catkin")
set(my_lidar_BUILDTOOL_EXPORT_DEPENDS )
set(my_lidar_EXEC_DEPENDS "rospy" "std_msgs")
set(my_lidar_RUN_DEPENDS "rospy" "std_msgs")
set(my_lidar_TEST_DEPENDS )
set(my_lidar_DOC_DEPENDS )
set(my_lidar_URL_WEBSITE "")
set(my_lidar_URL_BUGTRACKER "")
set(my_lidar_URL_REPOSITORY "")
set(my_lidar_DEPRECATED "")