set(_CATKIN_CURRENT_PACKAGE "lidar_filter")
set(lidar_filter_VERSION "0.0.0")
set(lidar_filter_MAINTAINER "nvidia <nvidia@todo.todo>")
set(lidar_filter_PACKAGE_FORMAT "2")
set(lidar_filter_BUILD_DEPENDS "rospy")
set(lidar_filter_BUILD_EXPORT_DEPENDS "rospy")
set(lidar_filter_BUILDTOOL_DEPENDS "catkin")
set(lidar_filter_BUILDTOOL_EXPORT_DEPENDS )
set(lidar_filter_EXEC_DEPENDS "rospy")
set(lidar_filter_RUN_DEPENDS "rospy")
set(lidar_filter_TEST_DEPENDS )
set(lidar_filter_DOC_DEPENDS )
set(lidar_filter_URL_WEBSITE "")
set(lidar_filter_URL_BUGTRACKER "")
set(lidar_filter_URL_REPOSITORY "")
set(lidar_filter_DEPRECATED "")